version: '3.8'
services:

  app:
    image: localhost/apm-demo:dev
    ports:
      - 5001:5001
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.26-arm64
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Adjust memory as needed
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.26-arm64
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  apm-server:
    image: docker.elastic.co/apm/apm-server:7.17.26-arm64
    ports:
      - 8200:8200
    depends_on:
      - elasticsearch
    environment:
      - output.elasticsearch.hosts=["elasticsearch:9200"]